### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by TotheSky0710** [hacess/chrome-extension-manifest-v3-screen-recording#1]
Hi.
First, thank you for your project so that I can use for my project.

I downloaded this project and installed on my browser.
But when I click start record button, I got this error message.
"Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist."

And when I clicked the start record button several times, then I got this error message.
"Unchecked runtime.lastError: Extension has not been invoked for the current page (see activeTab permission). Chrome pages cannot be captured."

So I couldn't run this extension on my browser.
Please let me know the solution.
Thank you.

**Comment by hacess** [comment]
@TotheSky0710  Chrome pages cannot be captured. means that you are trying to capture a chrome://, chrome-extension://, or similar Chrome specific page which is not allowed. Make sure the current page is http:// or https://.
